const galleryData = [
  {
    id: 1,
    title: "Training and Inter Class Debates",
    imageUrl: "./img/training-inter-class/tnl8.jpg",
    description:
      "Students engaging in training sessions and inter-class debate competitions.",
    images: [
      "./img/training-inter-class/tnl1.jpg",
      "./img/training-inter-class/tnl2.jpg",
      "./img/training-inter-class/tnl3.jpg",
      "./img/training-inter-class/tnl4.jpg",
      "./img/training-inter-class/tnl5.jpg",
      "./img/training-inter-class/tnl6.jpg",
      "./img/training-inter-class/tnl7.jpg",
      "./img/training-inter-class/tnl8.jpg",
    ],
  },
  {
    id: 2,
    title: "Radio Talk Show and Debates",
    imageUrl: "./img/radio-talk-show-debate/rts8.jpg",
    description:
      "Live radio debates and discussions featuring our talented debaters.",
    images: [
      "./img/radio-talk-show-debate/rts2.jpg",
      "./img/radio-talk-show-debate/rts3.jpg",
      "./img/radio-talk-show-debate/rts4.jpg",
      "./img/radio-talk-show-debate/rts5.jpg",
      "./img/radio-talk-show-debate/rts6.jpg",
      "./img/radio-talk-show-debate/rts7.jpg",
      "./img/radio-talk-show-debate/rts8.jpg",
    ],
  },
  {
    id: 3,
    title: "International Youth Day Debates 2024",
    imageUrl: "./img/international-youth-day/IYD7.jpg",
    description:
      "Special debate series celebrating International Youth Day 2024.",
    images: [
      "./img/international-youth-day/IYD1.jpg",
      "./img/international-youth-day/IYD2.jpg",
      "./img/international-youth-day/IYD3.jpg",
      "./img/international-youth-day/IYD4.jpg",
      "./img/international-youth-day/IYD5.jpg",
      "./img/international-youth-day/IYD6.jpg",
      "./img/international-youth-day/IYD7.jpg",
      "./img/international-youth-day/IYD8.jpg",
    ],
  },
  {
    id: 4,
    title: "Juba Schools Debate Championship 2024",
    imageUrl: "./img/juba-schools-debate24/JSDC24 (16).jpg",
    description:
      "The latest edition of our flagship schools debate championship.",
    images: [
      "./img/juba-schools-debate24/JSDC24 (1).jpg",
      "./img/juba-schools-debate24/JSDC24 (2).jpg",
      "./img/juba-schools-debate24/JSDC24 (3).jpg",
      "./img/juba-schools-debate24/JSDC24 (4).jpg",
      "./img/juba-schools-debate24/JSDC24 (5).jpg",
      "./img/juba-schools-debate24/JSDC24 (6).jpg",
      "./img/juba-schools-debate24/JSDC24 (7).jpg",
      "./img/juba-schools-debate24/JSDC24 (8).jpg",
      "./img/juba-schools-debate24/JSDC24 (9).jpg",
      "./img/juba-schools-debate24/JSDC24 (10).jpg",
      "./img/juba-schools-debate24/JSDC24 (11).jpg",
      "./img/juba-schools-debate24/JSDC24 (12).jpg",
      "./img/juba-schools-debate24/JSDC24 (13).jpg",
      "./img/juba-schools-debate24/JSDC24 (14).jpg",
      "./img/juba-schools-debate24/JSDC24 (15).jpg",
      "./img/juba-schools-debate24/JSDC24 (16).jpg",
      "./img/juba-schools-debate24/JSDC24 (17).jpg",
      "./img/juba-schools-debate24/JSDC24 (18).jpg",
      "./img/juba-schools-debate24/JSDC24 (19).jpg",
      "./img/juba-schools-debate24/JSDC24 (20).jpg",
      "./img/juba-schools-debate24/JSDC24 (21).jpg",
      "./img/juba-schools-debate24/JSDC24 (22).jpg",
      "./img/juba-schools-debate24/JSDC24 (23).jpg",
      "./img/juba-schools-debate24/JSDC24 (24).jpg",
      "./img/juba-schools-debate24/JSDC24 (25).jpg",
      "./img/juba-schools-debate24/JSDC24 (26).jpg",
      "./img/juba-schools-debate24/JSDC24 (27).jpg",
      "./img/juba-schools-debate24/JSDC24 (28).jpg",
      "./img/juba-schools-debate24/JSDC24 (29).jpg",
      "./img/juba-schools-debate24/JSDC24 (30).jpg",
    ],
  },
  {
    id: 5,
    title: "Juba Schools Debate Championship 2023",
    imageUrl: "./img/juba-schools-debate23/JSDC (6).jpg",
    description: "Highlights from last year's successful debate championship.",
    images: [
      "./img/juba-schools-debate23/JSDC (1).jpg",
      "./img/juba-schools-debate23/JSDC (2).jpg",
      "./img/juba-schools-debate23/JSDC (3).jpg",
      "./img/juba-schools-debate23/JSDC (4).jpg",
      "./img/juba-schools-debate23/JSDC (5).jpg",
      "./img/juba-schools-debate23/JSDC (6).jpg",
      "./img/juba-schools-debate23/JSDC (7).jpg",
      "./img/juba-schools-debate23/JSDC (8).jpg",
      "./img/juba-schools-debate23/JSDC (9).jpg",
      "./img/juba-schools-debate23/JSDC (10).jpg",
      "./img/juba-schools-debate23/JSDC (11).jpg",
      "./img/juba-schools-debate23/JSDC (12).jpg",
      "./img/juba-schools-debate23/JSDC (13).jpg",
      "./img/juba-schools-debate23/JSDC (14).jpg",
      "./img/juba-schools-debate23/JSDC (15).jpg",
      "./img/juba-schools-debate23/JSDC (16).jpg",
      "./img/juba-schools-debate23/JSDC (17).jpg",
    ],
  },
  {
    id: 6,
    title: "East African Debating Championship 2024",
    imageUrl: "./img/east-african-debating/east-african-debating1.jpg",
    description:
      "Regional championship featuring top debaters from East Africa.",
    images: [
      "./img/east-african-debating/east-african-debating1.jpg",
      "./img/east-african-debating/east-african-debating2.jpg",
      "./img/east-african-debating/east-african-debating3.jpg",
      "./img/east-african-debating/east-african-debating4.jpg",
      "./img/east-african-debating/east-african-debating5.jpg",
      "./img/east-african-debating/east-african-debating6.jpg",
      "./img/east-african-debating/east-african-debating7.jpg",
      "./img/east-african-debating/east-african-debating8.jpg",
      "./img/east-african-debating/east-african-debating9.jpg",
      "./img/east-african-debating/east-african-debating10.jpg",
      "./img/east-african-debating/east-african-debating11.jpg",
      "./img/east-african-debating/east-african-debating12.jpg",
      "./img/east-african-debating/east-african-debating13.jpg",
    ],
  },
  {
    id: 7,
    title: "Junub Debate Academy Open Tournament",
    imageUrl: "./img/jds-open/jds-open (1)",
    description:
      "Students engaging in debate for the Junub Debate Academy Open Tournament",
    images: [
      "./img/jds-open/jds-open (1)",
      "./img/jds-open/jds-open (2)",
      "./img/jds-open/jds-open (3)",
      "./img/jds-open/jds-open (4)",
      "./img/jds-open/jds-open (5)",
      "./img/jds-open/jds-open (6)",
      "./img/jds-open/jds-open (7)",
      "./img/jds-open/jds-open (8)",
      "./img/jds-open/jds-open (9)",
      "./img/jds-open/jds-open (10)",
      "./img/jds-open/jds-open (12)",
      "./img/jds-open/jds-open (13)",
      "./img/jds-open/jds-open (14)",
      "./img/jds-open/jds-open (15)",
      "./img/jds-open/jds-open (16)",
      "./img/jds-open/jds-open (17)",
      "./img/jds-open/jds-open (18)",
      "./img/jds-open/jds-open (19)",
      "./img/jds-open/jds-open (20)",
      "./img/jds-open/jds-open (21)",
      "./img/jds-open/jds-open (22)",
      "./img/jds-open/jds-open (23)",
      "./img/jds-open/jds-open (24)",
      "./img/jds-open/jds-open (25)",
      "./img/jds-open/jds-open (26)",
      "./img/jds-open/jds-open (27)",
      "./img/jds-open/jds-open (28)",
      "./img/jds-open/jds-open (29)",
      "./img/jds-open/jds-open (30)",
      "./img/jds-open/jds-open (31)",
      "./img/jds-open/jds-open (32)",
      "./img/jds-open/jds-open (33)",
      "./img/jds-open/jds-open (34)",
      "./img/jds-open/jds-open (35)",
      "./img/jds-open/jds-open (36)",
      "./img/jds-open/jds-open (37)",
      "./img/jds-open/jds-open (38)",
      "./img/jds-open/jds-open (39)",
      "./img/jds-open/jds-open (40)",
      "./img/jds-open/jds-open (41)",
      "./img/jds-open/jds-open (42)",
      "./img/jds-open/jds-open (43)",
      "./img/jds-open/jds-open (44)",
      "./img/jds-open/jds-open (45)",
      "./img/jds-open/jds-open (46)",
      "./img/jds-open/jds-open (47)",
      "./img/jds-open/jds-open (48)",
      "./img/jds-open/jds-open (49)",
      "./img/jds-open/jds-open (50)",
      "./img/jds-open/jds-open (51)",
      "./img/jds-open/jds-open (52)",
      "./img/jds-open/jds-open (53)",
      "./img/jds-open/jds-open (54)",
      "./img/jds-open/jds-open (55)",
      "./img/jds-open/jds-open (56)",
      "./img/jds-open/jds-open (57)",
      "./img/jds-open/jds-open (58)",
      "./img/jds-open/jds-open (59)",
      "./img/jds-open/jds-open (60)",
      "./img/jds-open/jds-open (61)",
      "./img/jds-open/jds-open (62)",
      "./img/jds-open/jds-open (63)",
      "./img/jds-open/jds-open (64)",
      "./img/jds-open/jds-open (65)",
      "./img/jds-open/jds-open (66)",
      "./img/jds-open/jds-open (67)",
      "./img/jds-open/jds-open (68)",
      "./img/jds-open/jds-open (69)",
      "./img/jds-open/jds-open (70)",
      "./img/jds-open/jds-open (71)",
      "./img/jds-open/jds-open (72)",
      "./img/jds-open/jds-open (73)",
      "./img/jds-open/jds-open (74)",
      "./img/jds-open/jds-open (75)",
      "./img/jds-open/jds-open (76)",
    ],
  },
];
