const galleryData = [
  {
    id: 1,
    title: "Training and Inter Class Debates",
    imageUrl: "../img/TICD/tnl1.jpg",
    description:
      "Students engaging in training sessions and inter-class debate competitions.",
    images: [
      "../img/TICD/tnl1.jpg",
      "../img/TICD/tnl2.jpg",
      "../img/TICD/tnl3.jpg",
      "../img/TICD/tnl4.jpg",
      "../img/TICD/tnl5.jpg",
      "../img/TICD/tnl6.jpg",
      "../img/TICD/tnl7.jpg",
      "../img/TICD/tnl8.jpg",
    ],
  },
  {
    id: 2,
    title: "Radio Talk Show and Debates",
    imageUrl: "../img/RTS-24/rts8.jpg",
    description:
      "Live radio debates and discussions featuring our talented debaters.",
    images: [
      "../img/RTS-24/rts2.jpg",
      "../img/RTS-24/rts3.jpg",
      "../img/RTS-24/rts4.jpg",
      "../img/RTS-24/rts5.jpg",
      "../img/RTS-24/rts6.jpg",
      "../img/RTS-24/rts7.jpg",
      "../img/RTS-24/rts8.jpg",
    ],
  },
  {
    id: 3,
    title: "International Youth Day Debates 2024",
    imageUrl: "../img/TIYD/IYD (1).jpg",
    description:
      "Special debate series celebrating International Youth Day 2024.",
    images: [
      "../img/TIYD/IYD (1).jpg",
      "../img/TIYD/IYD (2).jpg",
      "../img/TIYD/IYD (3).jpg",
      "../img/TIYD/IYD (4).jpg",
      "../img/TIYD/IYD (5).jpg",
      "../img/TIYD/IYD (6).jpg",
      "../img/TIYD/IYD (7).jpg",
      "../img/TIYD/IYD (8).jpg",
    ],
  },
  {
    id: 4,
    title: "Juba Schools Debate Championship 2024",
    imageUrl: "../img/JSDC24-second-edition/JSDC24 (16).jpg",
    description:
      "The latest edition of our flagship schools debate championship.",
    images: [
      "../img/JSDC24-second-edition/JSDC24 (1).jpg",
      "../img/JSDC24-second-edition/JSDC24 (2).jpg",
      "../img/JSDC24-second-edition/JSDC24 (3).jpg",
      "../img/JSDC24-second-edition/JSDC24 (4).jpg",
      "../img/JSDC24-second-edition/JSDC24 (5).jpg",
      "../img/JSDC24-second-edition/JSDC24 (6).jpg",
      "../img/JSDC24-second-edition/JSDC24 (7).jpg",
      "../img/JSDC24-second-edition/JSDC24 (8).jpg",
      "../img/JSDC24-second-edition/JSDC24 (9).jpg",
      "../img/JSDC24-second-edition/JSDC24 (10).jpg",
      "../img/JSDC24-second-edition/JSDC24 (11).jpg",
      "../img/JSDC24-second-edition/JSDC24 (12).jpg",
      "../img/JSDC24-second-edition/JSDC24 (13).jpg",
      "../img/JSDC24-second-edition/JSDC24 (14).jpg",
      "../img/JSDC24-second-edition/JSDC24 (15).jpg",
      "../img/JSDC24-second-edition/JSDC24 (16).jpg",
      "../img/JSDC24-second-edition/JSDC24 (17).jpg",
      "../img/JSDC24-second-edition/JSDC24 (18).jpg",
      "../img/JSDC24-second-edition/JSDC24 (19).jpg",
      "../img/JSDC24-second-edition/JSDC24 (20).jpg",
      "../img/JSDC24-second-edition/JSDC24 (21).jpg",
      "../img/JSDC24-second-edition/JSDC24 (22).jpg",
      "../img/JSDC24-second-edition/JSDC24 (23).jpg",
      "../img/JSDC24-second-edition/JSDC24 (24).jpg",
      "../img/JSDC24-second-edition/JSDC24 (25).jpg",
      "../img/JSDC24-second-edition/JSDC24 (26).jpg",
      "../img/JSDC24-second-edition/JSDC24 (27).jpg",
      "../img/JSDC24-second-edition/JSDC24 (28).jpg",
      "../img/JSDC24-second-edition/JSDC24 (29).jpg",
      "../img/JSDC24-second-edition/JSDC24 (30).jpg",
    ],
  },
  {
    id: 5,
    title: "Juba Schools Debate Championship 2023",
    imageUrl: "../img/juba-schools-debate24/juba-schools-debate",
    description: "Highlights from last year's successful debate championship.",
    images: [
      "/img/JSDC23-first-edition/JSDC (1).jpg",
      "/img/JSDC23-first-edition/JSDC (2).jpg",
      "/img/JSDC23-first-edition/JSDC (3).jpg",
      "/img/JSDC23-first-edition/JSDC (4).jpg",
      "/img/JSDC23-first-edition/JSDC (5).jpg",
      "/img/JSDC23-first-edition/JSDC (6).jpg",
      "/img/JSDC23-first-edition/JSDC (7).jpg",
      "/img/JSDC23-first-edition/JSDC (8).jpg",
      "/img/JSDC23-first-edition/JSDC (9).jpg",
      "/img/JSDC23-first-edition/JSDC (10).jpg",
      "/img/JSDC23-first-edition/JSDC (11).jpg",
      "/img/JSDC23-first-edition/JSDC (12).jpg",
      "/img/JSDC23-first-edition/JSDC (13).jpg",
      "/img/JSDC23-first-edition/JSDC (14).jpg",
      "/img/JSDC23-first-edition/JSDC (15).jpg",
      "/img/JSDC23-first-edition/JSDC (16).jpg",
      "/img/JSDC23-first-edition/JSDC (17).jpg",
    ],
  },
  {
    id: 6,
    title: "East African Debating Championship 2024",
    imageUrl: "../img/east-african-debating/east-african-debating1.jpg",
    description:
      "Regional championship featuring top debaters from East Africa.",
    images: [
      "../img/east-african-debating/east-african-debating1.jpg",
      "../img/east-african-debating/east-african-debating2.jpg",
      "../img/east-african-debating/east-african-debating3.jpg",
      "../img/east-african-debating/east-african-debating4.jpg",
      "../img/east-african-debating/east-african-debating5.jpg",
      "../img/east-african-debating/east-african-debating6.jpg",
      "../img/east-african-debating/east-african-debating7.jpg",
      "../img/east-african-debating/east-african-debating8.jpg",
      "../img/east-african-debating/east-african-debating9.jpg",
      "../img/east-african-debating/east-african-debating10.jpg",
      "../img/east-african-debating/east-african-debating11.jpg",
      "../img/east-african-debating/east-african-debating12.jpg",
      "../img/east-african-debating/east-african-debating13.jpg",
    ],
  },
];
