const galleryData = [
  {
    id: 1,
    title: "Training and Inter Class Debates",
    imageUrl: "./img/training-inter-class/tnl8.jpg",
    description:
      "Students engaging in training sessions and inter-class debate competitions.",
    images: [
      "./img/training-inter-class/tnl1.jpg",
      "./img/training-inter-class/tnl2.jpg",
      "./img/training-inter-class/tnl3.jpg",
      "./img/training-inter-class/tnl4.jpg",
      "./img/training-inter-class/tnl5.jpg",
      "./img/training-inter-class/tnl6.jpg",
      "./img/training-inter-class/tnl7.jpg",
      "./img/training-inter-class/tnl8.jpg",
    ],
  },
  {
    id: 2,
    title: "Radio Talk Show and Debates",
    imageUrl: "../img/radio-talk-show-debate/rts8.jpg",
    description:
      "Live radio debates and discussions featuring our talented debaters.",
    images: [
      "./img/radio-talk-show-debate/rts2.jpg",
      "./img/radio-talk-show-debate/rts3.jpg",
      "./img/radio-talk-show-debate/rts4.jpg",
      "./img/radio-talk-show-debate/rts5.jpg",
      "./img/radio-talk-show-debate/rts6.jpg",
      "./img/radio-talk-show-debate/rts7.jpg",
      "./img/radio-talk-show-debate/rts8.jpg",
    ],
  },
  {
    id: 3,
    title: "International Youth Day Debates 2024",
    imageUrl: "../img/international-youth-day/IYD7.jpg",
    description:
      "Special debate series celebrating International Youth Day 2024.",
    images: [
      "./img/international-youth-day/IYD1.jpg",
      "./img/international-youth-day/IYD2.jpg",
      "./img/international-youth-day/IYD3.jpg",
      "./img/international-youth-day/IYD4.jpg",
      "./img/international-youth-day/IYD5.jpg",
      "./img/international-youth-day/IYD6.jpg",
      "./img/international-youth-day/IYD7.jpg",
      "./img/international-youth-day/IYD8.jpg",
    ],
  },
  {
    id: 4,
    title: "Juba Schools Debate Championship 2024",
    imageUrl: "../img/juba-schools-debate24/JSDC24 (16).jpg",
    description:
      "The latest edition of our flagship schools debate championship.",
    images: [
      "./img/juba-schools-debate24/JSDC24 (1).jpg",
      "./img/juba-schools-debate24/JSDC24 (2).jpg",
      "./img/juba-schools-debate24/JSDC24 (3).jpg",
      "./img/juba-schools-debate24/JSDC24 (4).jpg",
      "./img/juba-schools-debate24/JSDC24 (5).jpg",
      "./img/juba-schools-debate24/JSDC24 (6).jpg",
      "./img/juba-schools-debate24/JSDC24 (7).jpg",
      "./img/juba-schools-debate24/JSDC24 (8).jpg",
      "./img/juba-schools-debate24/JSDC24 (9).jpg",
      "./img/juba-schools-debate24/JSDC24 (10).jpg",
      "./img/juba-schools-debate24/JSDC24 (11).jpg",
      "./img/juba-schools-debate24/JSDC24 (12).jpg",
      "./img/juba-schools-debate24/JSDC24 (13).jpg",
      "./img/juba-schools-debate24/JSDC24 (14).jpg",
      "./img/juba-schools-debate24/JSDC24 (15).jpg",
      "./img/juba-schools-debate24/JSDC24 (16).jpg",
      "./img/juba-schools-debate24/JSDC24 (17).jpg",
      "./img/juba-schools-debate24/JSDC24 (18).jpg",
      "./img/juba-schools-debate24/JSDC24 (19).jpg",
      "./img/juba-schools-debate24/JSDC24 (20).jpg",
      "./img/juba-schools-debate24/JSDC24 (21).jpg",
      "./img/juba-schools-debate24/JSDC24 (22).jpg",
      "./img/juba-schools-debate24/JSDC24 (23).jpg",
      "./img/juba-schools-debate24/JSDC24 (24).jpg",
      "./img/juba-schools-debate24/JSDC24 (25).jpg",
      "./img/juba-schools-debate24/JSDC24 (26).jpg",
      "./img/juba-schools-debate24/JSDC24 (27).jpg",
      "./img/juba-schools-debate24/JSDC24 (28).jpg",
      "./img/juba-schools-debate24/JSDC24 (29).jpg",
      "./img/juba-schools-debate24/JSDC24 (30).jpg",
    ],
  },
  {
    id: 5,
    title: "Juba Schools Debate Championship 2023",
    imageUrl: "/img/juba-schools-debate23/JSDC (6).jpg",
    description: "Highlights from last year's successful debate championship.",
    images: [
      "./img/juba-schools-debate23/JSDC (1).jpg",
      "./img/juba-schools-debate23/JSDC (2).jpg",
      "./img/juba-schools-debate23/JSDC (3).jpg",
      "./img/juba-schools-debate23/JSDC (4).jpg",
      "./img/juba-schools-debate23/JSDC (5).jpg",
      "./img/juba-schools-debate23/JSDC (6).jpg",
      "./img/juba-schools-debate23/JSDC (7).jpg",
      "./img/juba-schools-debate23/JSDC (8).jpg",
      "./img/juba-schools-debate23/JSDC (9).jpg",
      "./img/juba-schools-debate23/JSDC (10).jpg",
      "./img/juba-schools-debate23/JSDC (11).jpg",
      "./img/juba-schools-debate23/JSDC (12).jpg",
      "./img/juba-schools-debate23/JSDC (13).jpg",
      "./img/juba-schools-debate23/JSDC (14).jpg",
      "./img/juba-schools-debate23/JSDC (15).jpg",
      "./img/juba-schools-debate23/JSDC (16).jpg",
      "./img/juba-schools-debate23/JSDC (17).jpg",
    ],
  },
  {
    id: 6,
    title: "East African Debating Championship 2024",
    imageUrl: "../img/east-african-debating/east-african-debating1.jpg",
    description:
      "Regional championship featuring top debaters from East Africa.",
    images: [
      "./img/east-african-debating/east-african-debating1.jpg",
      "./img/east-african-debating/east-african-debating2.jpg",
      "./img/east-african-debating/east-african-debating3.jpg",
      "./img/east-african-debating/east-african-debating4.jpg",
      "./img/east-african-debating/east-african-debating5.jpg",
      "./img/east-african-debating/east-african-debating6.jpg",
      "./img/east-african-debating/east-african-debating7.jpg",
      "./img/east-african-debating/east-african-debating8.jpg",
      "./img/east-african-debating/east-african-debating9.jpg",
      "./img/east-african-debating/east-african-debating10.jpg",
      "./img/east-african-debating/east-african-debating11.jpg",
      "./img/east-african-debating/east-african-debating12.jpg",
      "./img/east-african-debating/east-african-debating13.jpg",
    ],
  },
];
